### model
model_name_or_path: Qwen/Qwen3-VL-2B-Instruct
image_max_pixels: 262144
video_max_pixels: 16384
trust_remote_code: true
flash_attn: fa2

### method
stage: beft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all
beft_prior_modeling: mlp_head
beft_prior_head_num_layers: 2
beft_prior_head_proj_dim: 256
beft_use_prior_head_loss: true
beft_prior_loss_factor: 1.0

### dataset
dataset: beft_mllm_demo
template: qwen3_vl_nothink
cutoff_len: 1024
max_samples: 8
preprocessing_num_workers: 1
dataloader_num_workers: 0
packing: false
neat_packing: false

### output
output_dir: saves/qwen3-vl-2b/lora/beft
logging_steps: 1
save_steps: 5
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
beft_prior_head_lr: 1.0e-4
max_steps: 5
lr_scheduler_type: cosine
warmup_ratio: 0.0
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null
